spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://cityfix.cu2q8w9ppipu.eu-west-3.rds.amazonaws.com:3306/cityfix
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver

